### ISSUE TITLE
Criar backend

### ISSUE THREAD

**Issue by bernardocamps** [bernardocamps/quotes#1]
Encontrar uma fonte pública de Quotes e integrar ao site.

**Comment by bernardocamps** [comment]
https://forum.freecodecamp.org/t/free-api-inspirational-quotes-json-with-code-examples/311373

**Comment by mpinheir** [comment]
Acho que seria bacana conseguir uma fonte de quotes em Português. Se não conseguir vamos criar um backend e colocar em algum canto.

**Comment by bernardocamps** [comment]
No [WikiQuotes](https://pt.wikiquote.org/wiki/Página_principal) tem, mas não consegui encontrar um link igual aquele que gera o resultado no formato JSON. 

Encontrei esse link explicando como acessar os dados, mas ainda não entendi muito bem como funciona: https://wikimedia.org/api/rest_v1/

**Comment by bernardocamps** [comment]
No WikiQuotes tem, mas não encontrei o link igual aquele que gera o resultado no formato JSON.

Encontrei esse link explicando como acessar os dados, mas ainda não entendi muito bem como funciona: https://wikimedia.org/api/rest_v1/

**Comment by mpinheir** [comment]
Que fazer o backend?

**Comment by bernardocamps** [comment]
> Que fazer o backend?

Topo! Qual linguagem e onde hospedar?

**Comment by bernardocamps** [comment]
API do TitenQ no Heroku: https://api-adonisjs.herokuapp.com

**Comment by mpinheir** [comment]
heroku
