### ISSUE TITLE
Adicionar esquema de themas

### ISSUE THREAD

**Issue by brunoom1** [bernardocamps/quotes#20]
A ideia é organizar o CSS de tal forma, que para criar um tema novo seria só duplicar uma pasta e trabalhar o CSS.

Minha sugestão é reorganizar o CSS para usar o sass. 

Os temas poderiam estar disponíveis no site através de uma uma lista com o nome do tema e a cor.

Ao clicar no tema este poderia ser salvo em localstorw para manter as configs do usuário.

**Comment by brunoom1** [comment]
E ai, o que acha dessa ideia @bernardocamps ?

**Comment by bernardocamps** [comment]
Muito bacana Bruno! Não conheço o SASS. A versão em inglês que está em Express/NodeJS em outra pasta não herdou esse novo visual pois usa outro CSS, você consegue juntá-los?

**Comment by brunoom1** [comment]
Legal, vou abrir uma insue aqui para alinhar, mas o ideial não seria manter somente uma versão?

**Comment by mpinheir** [comment]
@brunoom1  temas do que? Cores? Que tipo de temas?

**Comment by brunoom1** [comment]
@mpinheir Isso mesmo, pensei em tema de cores, talvez imagens. Mais ou menos como acontece com trello. Seria algo simples. Criamos um padrão de estilo para que outras pessoas possam também criar temas. E ao selecionar um tema essa informação seria salva em localStorage.

**Comment by mpinheir** [comment]
@brunoom1 Prepara um protótipo para nós termos uma ideia do que você tem em mente.

**Comment by brunoom1** [comment]
Legal, vou bolar algo no figma e passo aqui. Só ter um tempinho no trampo.

**Comment by brunoom1** [comment]
Fala galera, dei uma corridinha aqui e fiz um protótipo mais ou menos!
https://www.figma.com/proto/BVY5j73s2szlit6QcrpJvC/Prototipo?node-id=1%3A3&scaling=min-zoom&page-id=0%3A1
É só uma ideia, se acharem melhor não implementar, entendo e vamos seguindo com as melhorias. 
Abraços!

**Comment by bernardocamps** [comment]
Curti pra caramba também, ficou show!
