### ISSUE TITLE
Padronização do CSS para as duas versões do projeto

### ISSUE THREAD

**Issue by brunoom1** [bernardocamps/quotes#22]
Este projeto, atualmente está com duas versões no mesmo repositório. 
A primeira, uma versão em HTML simples e a segunda a versão inglês que conta com uma estrutura mais robusta com Express/NodeJS.
O CSS da parte mais simples foi alterado e foi adicionado algumas modificações para o botão de reloading e efeito de carregamento que devem também ser aplicados  também na segunda versão, a versão em inglês. 

Citado abaixo: 
_Originally posted by @bernardocamps in https://github.com/bernardocamps/quotes/issues/20#issuecomment-809761221_

**Comment by mpinheir** [comment]
@brunoom1 Melhora o titulo do issue para ficar mais claro.

**Comment by brunoom1** [comment]
Verdade, adicionei na correria acabou não ficando claro! Vou ajustar. Obrigado.

**Comment by bernardocamps** [comment]
Ah, um detalhe importante, a outra versão (em inglês/NodeJS) utiliza outro arquivo JavaScript para controlar o botão refresh... ele não possui as novas features de animação.
