### ISSUE TITLE
Migrar o banco do projeto de MongoDB pra MariaDB

### ISSUE THREAD

**Issue by mpinheir** [bernardocamps/quotes#29]
A versão MongoDB usada pelo BACKEND em NodeJS restringe o tamanho do banco a 512 MB.
Outro fator é que cria uma dependência para o serviço cloud do MongoDB que é um serviço comercial.
O ideal é uma solução de banco de dados que possa ser colocada em um container e que este container possa ser colocado em quaquer serviço onde containers possam ser executados e storage possa ser persistida.

**Comment by brunoom1** [comment]
Fala pessoal. Nas últimas alterações que enviei, adicionei as configurações para essa mudança. Peço que deem uma olhadinha por favor. Abraços.
PR: https://github.com/bernardocamps/quotes/pull/32

**Comment by bernardocamps** [comment]
Boa tarde, @mpinheir e @brunoom1 . Até essa semana eu nunca tinha usado o Docker, então peço a ajuda de vocês para verificar os incrementos que fiz. Vou descrever os passos:

- Criei um container (quote_database) e importei a imagem oficial do MariaDB no Docker Hub.
- Adicionei o volume local para apontar para a pasta **/backend/db** e persistir os dados inseridos.
- No banco de dados, criei a database **quote** e dentro da mesma a tabela **Quotes** utilizando o seguinte comando:
```
CREATE TABLE Quotes ( 
id INT(11) NOT NULL AUTO_INCREMENT, 
text varchar(1000), 
author varchar (100), 
PRIMARY KEY (id) 
);
```
- Importei o **quotes.csv** da versão em Go utilizando o aplicativo Sequel Pro.
- Ajustei o arquivo **docker-compose.yml**, adicionando as variáveis de ambiente e apontando para os dados persistidos.

**Comment by brunoom1** [comment]
@bernardocamps Fala meu camarada. Tudo bem? Então, tenho algumas observações: 

- A estrutura que eu defini já trabalha a criação do banco de dados. Eu deveria ter comentado isso no PR. O ORM - TYPEORM https://typeorm.io/#/ sincroniza automaticamente a estrutura do [schema](https://github.com/bernardocamps/quotes/blob/master/backend/src/entity/quote.js), com as tabelas do banco de dados. 
A importação de dados por padrão, devem acontecer através de um script de importação de dados. 
Não devemos versionar os arquivos da estrutura do mysql, se fizermos isso vamos ter conflitos a cada teste. Só versionamos arquivos que de fato editamos.

**Comment by bernardocamps** [comment]
- Eita! 😅 Mas foi ótimo, aprendi muita coisa esses dias! Valeu o aprendizado. Até então não sabia como eram os containers e só tinha usado banco de dados NoSQL (MongoDB).

- Sobre o não versionamento do MySQL, eu deveria ter colocado toda a pasta **db** no .gitignore ou deixaria de fora a subpasta **/db/quote/** para que o usuário pudesse ter já as primeiras quotes no arquivo?

**Comment by brunoom1** [comment]
> * Eita! 😅 Mas foi ótimo, aprendi muita coisa esses dias! Valeu o aprendizado. Até então não sabia como eram os containers e só tinha usado banco de dados NoSQL (MongoDB).

Com certeza, o aprender é o principal e em minha opinião, o mais gostoso. 

> * Sobre o não versionamento do MySQL, eu deveria ter colocado toda a pasta **db** no .gitignore ou deixaria de fora a subpasta **/db/quote/** para que o usuário pudesse ter já as primeiras quotes no arquivo?

Normalmente, não vesionamos dados. O que versionamos é a estrutura e criamos scripts que adicionam dados iniciais ao nosso banco a fim de facilitar o desenvolvimento e testes. Para não termos que sempre adicionar dados antes de começar a alterar.
A estrutura do banco, normalmente é versionada a partir de arquivos construtores da base de dados. Esses arquivos são chamados as migrations. Elas criam o banco de dados incial e trabalham qualquer mudança necessária posteriormente. 
E para a adição de arquivos iniciais a esse banco, usamos as seeds. São scripts que preenchem o nosso banco com dados, normalmente fake, para que possamos testar nossa instalação de maneira rápida.
o docker-compose sobe uma instância do banco mariadb com uma base inicial. Porém, mas realmente você não vai conseguir acessar o banco, por que eu deveira ter exportado as portas de acesso ao banco. 3306. No meu ambiente funcionou, por que eu utilizo o banco e a app dentro de containers e os colocos na mesma rede, através do comando docker network. Também é bem legal conhecer. De qualuqer forma, vou editar o arquivo e exportar a porta 3306.

> * Ah, onde estão armazenadas as quotes da versão com TYPEORM? Tentei acessar o container mas não consegui retorno da API. Não sei se faltou configurar alguma coisa no meu Docker, ainda estou aprendendo a usá-lo.

Como disse antes, o banco está dentro do container. Porém, como não exportei a porta, não é possível acessar o banco através da maquina HOST. Vacilo meu. E outra coisa, como disse antes, o banco de dados nunca inicia cheio.

**Comment by bernardocamps** [comment]
Legal d+++! Obrigado pelas explicações, @brunoom1 ! Não conhecia! Vou dar uma estudada sobre! Vou desfazer os commits aqui então pra voltar pra verdão anterior! 😁👍🏻

**Comment by brunoom1** [comment]
> Legal d+++! Obrigado pelas explicações, @brunoom1 ! Não conhecia! Vou dar uma estudada sobre! Vou desfazer os commits aqui então pra voltar pra verdão anterior! 😁👍🏻

Blz. Eu já faço as alterações para exportar a porta do DB

**Comment by bernardocamps** [comment]
Fala @brunoom1 , beleza? Já dei merge no último PR! Te perguntar, para iniciar o DB, você comentou do Seeds... procurei aqui para estudar mas só encontrei pra Lavarel/PHP. Você tem algum link/tutorial/documentação que eu possa estudar para aprender a utilizar essa funcionalidade pro MariaDB?

**Comment by brunoom1** [comment]
Eu vou configurar as seeds no projeto, acho que vai ficar mais claro. As seeds, são scripts que criam informações padrões no banco para que ele não esteja vazio no início da aplicação. Ou seja, um script que rode um linhas de inserção no banco, podem ser considerados seeds.
