### ISSUE TITLE
Criar containers separados para o front end, back end e para o banco de dados

### ISSUE THREAD

**Issue by mpinheir** [bernardocamps/quotes#30]
A ideia é criar containers que possam ser executados com simplicidade na máquina de quem quer se seja ou em serviços que executam containers. Isso aumentará a flexibilidade e portabilidade da solução.

**Comment by bernardocamps** [comment]
Atenção: docker-compose para criação do container do MariaDB adicionado ao backend pelo Gabriel.

**Comment by bernardocamps** [comment]
Pendente: container para o Front End.

**Comment by mpinheir** [comment]
Eu criei o docker file para o backend em go e coloquei o arquiv no repo do backend no github e a imagem está no dockerhub.
